### ISSUE TITLE
Non exclusion des paquets php différents

### ISSUE THREAD

**Issue by senseicoder** [Epiconcept-Paris/infra-build-php#1]
A vérifier, mais en installant 5.6 sur un serveur avec déjà la 7.1, aucun conflit signalé

sudo apt purge epi-php-7.1-cli epi-php-7.1-mod epi-php-7.1-mysql
sudo apt install epi-php-5.6-mod epi-php-5.6-cli

**Comment by cdtepi** [comment]
Discussion le 12.8.2019: il s'agit à l'install d'un mod d'exclure les autres mod et tous les fpm
pour ne pas avoir a faire le apt purge
