### ISSUE TITLE
Désinstallation incomplète pour paquet PHP

### ISSUE THREAD

**Issue by senseicoder** [Epiconcept-Paris/infra-build-php#2]
après avoir retiré php-7.1, restart Apache
apache2_reload: Your configuration is broken. Not restarting Apache 2
apache2_reload: apache2: Syntax error on line 146 of /etc/apache2/apache2.conf: Syntax error on line 1 of /etc/apache2/mods-enabled/php7.1.load: Cannot load /usr/lib/apache2/modules/libphp7.1.so into server: /usr/lib/apache2/modules/libphp7.1.so: cannot open shared object file: No such file or directory

Il faut un sudo a2dismod php7.1 puis restart

**Comment by cdtepi** [comment]
Discussion le 12.8.2019: bloque le start d'Apache
