### ISSUE TITLE
activer conf spécifique epiconcept sur changement de paquet

### ISSUE THREAD

**Issue by senseicoder** [Epiconcept-Paris/infra-build-php#3]
sudo mkdir /etc/php/5.6/conf.d
sudo ln /etc/epiconcept/php-mods-available/epiconcept.ini /etc/php/5.6/conf.d
sudo ln /etc/epiconcept/php-mods-available/epiconcept_apc.ini /etc/php/5.6/conf.d

à voir si c'est une procédure de bascule de version, ou à intégrer (sans doute mauvaise idée d'intégrer)

**Comment by cdtepi** [comment]
Discussion le 12.8.2019: faire qq chose d'assez générique pour tous les fichiers .ini dans /etc/epiconcept/php-mods-available
